DECLARE

BEGIN
   SELECT COUNT (*) FROM DEPART WHERE DEPT_NO = 99;

   INSERT INTO DEPART VALUES (99, 'TEMPORAL', 'TEMPORAL');
   
   UPDATE EMPLE SET DEPT_NO = 99 WHERE DEPT_NO = 10;

   DELETE FROM DEPART WHERE DEPT_NO = 10;

END;
/